<?php

/**
 * Implementation of hook_perm().
 */
function hontza_grupos_perm() {
  return array('selector de grupos');
}

function hontza_grupos_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':
      //Crear un vocabulario para cada grupo creado asociandolo.
      if ($node-> type=='grupo') {
         $vocabulary = array(
            'name'  => $node->purl['value'],
            'description' => $node->og_description,
            'multiple'  => 1,
            'required'  => 0,
            'hierarchy' => 1,
            'relations' => 0,
            'nodes' => array('canal_busqueda' => 1, 'canal_de_supercanal' => 1, 'canal_de_yql' => 1),
            'weight'        => 0,
            'og' => $node->nid,
        );
        taxonomy_save_vocabulary($vocabulary);
      }
    break;
    case 'presave':
            break;
    case 'delete':
          break;
    case 'load':
      
    break;
  }
}

/**
 *Implementation of hook_form_alter
 */
function hontza_grupos_form_alter(&$form, &$form_state, $form_id) {
  
}

/**
 * Implementation of hook_menu
 */
function hontza_grupos_menu() {
  $items = array();
  $items['mis-grupos'] = array(
    'page callback' => 'drupal_get_form',    
    'page arguments'   => array('mis_grupos', 2),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'access arguments' => array('selector de grupos'),
  );
  return $items;
}

/**
 * Form para mostrar grupos
 *
 */
function mis_grupos() {
  if (user_access('selector de grupos')) {
  drupal_set_title("Mis grupos");
  global $user;
  $form = array();
    $form['grupos'] = array(
      '#type' => 'fieldset',
      '#title' => t('Mis grupos'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
  $header = array(
  array('data' => t('Nombre del grupo'), 'field' => 'node_title'),
  array('data' => t('Tipo de grupo'), 'field' => 'term_data_name'),
  array('data' => t('Usuarios en el grupo'), 'field' => 'member_count'),
  array('data' => t('Acceder al grupo'), 'field' => 'enlace'),
  );
    
$consulta= db_query("SELECT node.nid AS nid,
        node.title AS node_title,
        term_data.name AS term_data_name,
        term_data.vid AS term_data_vid,
        term_data.tid AS term_data_tid,
        p.value AS enlace,
        (SELECT COUNT(*) FROM og_uid ou INNER JOIN users u ON ou.uid = u.uid WHERE ou.nid = og.nid AND u.status > 0 AND ou.is_active >= 1 AND ou.is_admin >= 0 ) AS member_count
        FROM node node 
        LEFT JOIN term_node term_node ON node.vid = term_node.vid
        LEFT JOIN term_data term_data ON term_node.tid = term_data.tid
        LEFT JOIN og og ON node.nid = og.nid
        LEFT JOIN purl p ON og.nid = p.id
        LEFT JOIN og_uid ug ON og.nid = ug.nid   
        WHERE (node.type in ('grupo')) AND (node.status <> 0) AND ug.uid = %d", $user->uid);
  
  while ($data = db_fetch_object($consulta)) {
      
  $rows[] = array(l($data->node_title, $data->enlace .'/dashboard'), $data->term_data_name, $data->member_count, l('Entrar', $data->enlace .'/dashboard'));
  }
    $out = theme('table', $header, $rows);
    $out .= theme( 'pager', NULL, $limit, 0 );
    $form['grupos']['lista'] = array(
          '#type' => 'item',
          '#value' =>  $out,
    );
  return $form;
  }
  else{
  drupal_set_title('No tiene permisos.');
  }
}





